<?php

/*
 * test de la classe emploi du temps
 *
 */
$topdir = "../";


require_once ($topdir . "include/cts/edt_img.inc.php");

$lines = array(array ("hr_deb_seance" => "14h00",
		      "hr_fin_seance" => "16h00",
		      "jour_seance" => "Vendredi",
		      "semaine_seance" => "T",
		      "type_seance" => "Cours",
		      "nom_uv" => "AG41",
		      "salle_seance" => "E107"),
	       array ("hr_deb_seance" => "10h15",
		      "hr_fin_seance" => "12h15",
		      "jour_seance" => "Jeudi",
		      "semaine_seance" => "T",
		      "type_seance" => "TD",
		      "grp_seance" => "3",
		      "nom_uv" => "AG41",
		      "salle_seance" => "A205"),
	       array ("hr_deb_seance" => "16h15",
		      "hr_fin_seance" => "18h15",
		      "jour_seance" => "Lundi",
		      "type_seance" => "TP",
		      "semaine_seance" => "A",
		      "grp_seance" => "2",
		      "nom_uv" => "AG41",
		      "salle_seance" => "B403"),
	       array ("hr_deb_seance" => "10h15",
		      "hr_fin_seance" => "12h15",
		      "semaine_seance" => "T",
		      "jour_seance" => "Lundi",
		      "type_seance" => "Cours",
		      "nom_uv" => "IN41",
		      "salle_seance" => "A203"),
	       array ("hr_deb_seance" => "16h15",
		      "hr_fin_seance" => "18h15",
		      "jour_seance" => "Mercredi",
		      "semaine_seance" => "T",
		      "type_seance" => "TD",
		      "grp_seance" => "1",
		      "nom_uv" => "IN41",
		      "salle_seance" => "A310"),
	       array ("hr_deb_seance" => "16h15",
		      "hr_fin_seance" => "18h15",
		      "jour_seance" => "Lundi",
		      "type_seance" => "TP",
		      "semaine_seance" => "B",
		      "grp_seance" => "1",
		      "nom_uv" => "IN41",
		      "salle_seance" => "B404"),
	       array ("hr_deb_seance" => "08h00",
		      "hr_fin_seance" => "10h00",
		      "jour_seance" => "Mardi",
		      "semaine_seance" => "T",
		      "type_seance" => "Cours",
		      "nom_uv" => "RE41",
		      "salle_seance" => "A200"),
	       array ("hr_deb_seance" => "14h00",
		      "hr_fin_seance" => "16h00",
		      "jour_seance" => "Mercredi",
		      "type_seance" => "TD",
		      "semaine_seance" => "T",
		      "grp_seance" => "3",
		      "nom_uv" => "RE41",
		      "salle_seance" => "A314"),
	       array ("hr_deb_seance" => "16h15",
		      "hr_fin_seance" => "19h15",
		      "jour_seance" => "Vendredi",
		      "type_seance" => "TP",
		      "semaine_seance" => "A",
		      "grp_seance" => "2",
		      "nom_uv" => "RE41",
		      "salle_seance" => "B405"),
	       array ("hr_deb_seance" => "14h00",
		      "hr_fin_seance" => "16h00",
		      "jour_seance" => "Lundi",
		      "type_seance" => "Cours",
		      "nom_uv" => "MT41",
		      "semaine_seance" => "T",
		      "salle_seance" => "A203"),
	       array ("hr_deb_seance" => "10h15",
		      "hr_fin_seance" => "12h15",
		      "jour_seance" => "Vendredi",
		      "type_seance" => "TD",
		      "semaine_seance" => "T",
		      "grp_seance" => "2",
		      "nom_uv" => "MT41",
		      "salle_seance" => "A210"),
	       array ("hr_deb_seance" => "08h00",
		      "hr_fin_seance" => "10h00",
		      "jour_seance" => "Lundi",
		      "type_seance" => "TD",
		      "semaine_seance" => "T",
		      "grp_seance" => "2",
		      "nom_uv" => "LS02",
		      "salle_seance" => "A312"),
	       array ("hr_deb_seance" => "13h00",
		      "hr_fin_seance" => "14h00",
		      "jour_seance" => "Mercredi",
		      "type_seance" => "TP",
		      "semaine_seance" => "T",
		      "grp_seance" => "3",
		      "nom_uv" => "LS02",
		      "salle_seance" => "A305"),
	       array ("hr_deb_seance" => "13h00",
		      "semaine_seance" => "T",
		      "hr_fin_seance" => "14h00",
		      "jour_seance" => "Mardi",
		      "type_seance" => "Cours",
		      "nom_uv" => "MG02",
		      "salle_seance" => "A306"),
	       array ("hr_deb_seance" => "14h00",
		      "hr_fin_seance" => "16h00",
		      "semaine_seance" => "T",
		      "jour_seance" => "Mardi",
		      "type_seance" => "TD",
		      "grp_seance" => "1",
		      "nom_uv" => "MG02",
		      "salle_seance" => "A306"));


$edt_pedrov = new edt_img ("Pierre Mauduit",
		       $lines,
		       "/var/www/ae/www/taiste/images/logo_utbm_edt.png");

$edt_pedrov->generate ();

?>
